# Generated by Django 3.2.3 on 2021-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('Email_ID', models.EmailField(default='', max_length=100)),
                ('contact_No', models.CharField(default='', max_length=50)),
                ('Adress', models.CharField(default='', max_length=100)),
                ('Crime', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReportAnonymously',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crime', models.TextField(default='')),
            ],
        ),
    ]
