# Generated by Django 3.2.3 on 2021-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Location_of_Crime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reportanonymously',
            name='Location_of_Crime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reportanonymously',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
