# Generated by Django 3.2.3 on 2021-05-26 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20210526_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 19, 38, 33, 774750)),
        ),
        migrations.AlterField(
            model_name='reportanonymously',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 19, 38, 33, 773749)),
        ),
    ]
